### ISSUE TITLE
problem with mocking i18next module

### ISSUE THREAD

**Issue by PerpetualWar** [panter/vue-i18next#18]
Hi, 

I want to setup test environment for existing Vue project with jest and vue-test-utils. 

However I have a problem with mocking i18next module.

```
jest.mock('i18next', () => ({
  use: () => ({
    init: () => ({
      t: k => k,
      on: () => {}
    })
  })
}));
```
this mock throws this error: 

```

  TypeError: this.i18next.on is not a function

      38 |      .init(i18nextOptions);
      39 |
    > 40 | export default new VueI18Next(i18next);
      41 |

      at new n (node_modules/@panter/vue-i18next/dist/vue-i18next.js:1:3444)
      at Object.<anonymous> (src/app/locale/i18n.js:40:1)
      at Object.<anonymous> (src/app/store/modules/account/mutations.js:6:13)
      at Object.<anonymous> (src/app/store/modules/account/index.js:7:18)
      at Object.<anonymous> (src/app/store/index.js:17:16)
      at src/app/pages/home/index/index.vue:24:14
      at Object.<anonymous> (src/app/pages/home/index/index.vue:230:3)
      at Object.<anonymous> (test/unit/home.spec.js:17:187)
```

Without mock whatsoever, it just says i18next is undefined. 

https://stackoverflow.com/questions/48789110/how-to-mock-i18next-module-in-jest
https://github.com/i18next/i18next/issues/1017

Any help is appreciated.

**Comment by claudiocro** [comment]
Hi! did you already find a solution for it, or else I will look into it

**Comment by PerpetualWar** [comment]
Nope, no solution yet unfortunately.

**Comment by xJREB** [comment]
Wouldn't it be an option to instantiate it in your component tests? Here's what we do:

```TypeScript
import VueI18Next from "@panter/vue-i18next";
import { createLocalVue, shallowMount } from "@vue/test-utils";
import i18next from "i18next";
import Vue from "vue";
import i18nDe from "../src/i18n/de";
import i18nEn from "../src/i18n/en";

describe("Your Component Test", () => {
    const localVue = createLocalVue();
    localVue.use(VueI18Next);
    i18next.init({
        lng: "en",
        resources: {
            en: { translation: i18nEn },
            de: { translation: i18nDe }
        }
    });
    const i18n = new VueI18Next(i18next);

    const wrapper = shallowMount(YourComponent, {
        localVue,
        i18n
    });

    it("should be a vue instance", () => {
        expect(wrapper.isVueInstance()).toBeTruthy();
    });

...
});
```

**Comment by jqweryjson** [comment]
For me:
1. Mock all plugin entirely => jest.mock('@panter/vue-i18next')
2. Mock => $i18n: {i18next: {language: 'en'}}
